onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /hdl_top/axi_intf/aclk
add wave -noupdate /hdl_top/axi_intf/aresetn
add wave -noupdate /hdl_top/axi_intf/awid
add wave -noupdate /hdl_top/axi_intf/awaddr
add wave -noupdate /hdl_top/axi_intf/awlen
add wave -noupdate /hdl_top/axi_intf/awsize
add wave -noupdate /hdl_top/axi_intf/awburst
add wave -noupdate /hdl_top/axi_intf/awlock
add wave -noupdate /hdl_top/axi_intf/awcache
add wave -noupdate /hdl_top/axi_intf/awprot
add wave -noupdate /hdl_top/axi_intf/awqos
add wave -noupdate /hdl_top/axi_intf/awregion
add wave -noupdate /hdl_top/axi_intf/awuser
add wave -noupdate /hdl_top/axi_intf/awvalid
add wave -noupdate /hdl_top/axi_intf/awready
add wave -noupdate /hdl_top/axi_intf/wdata
add wave -noupdate /hdl_top/axi_intf/wstrb
add wave -noupdate /hdl_top/axi_intf/wlast
add wave -noupdate /hdl_top/axi_intf/wuser
add wave -noupdate /hdl_top/axi_intf/wvalid
add wave -noupdate /hdl_top/axi_intf/wready
add wave -noupdate /hdl_top/axi_intf/bid
add wave -noupdate /hdl_top/axi_intf/bresp
add wave -noupdate /hdl_top/axi_intf/buser
add wave -noupdate /hdl_top/axi_intf/bvalid
add wave -noupdate /hdl_top/axi_intf/bready
add wave -noupdate /hdl_top/axi_intf/arid
add wave -noupdate /hdl_top/axi_intf/araddr
add wave -noupdate /hdl_top/axi_intf/arlen
add wave -noupdate /hdl_top/axi_intf/arsize
add wave -noupdate /hdl_top/axi_intf/arburst
add wave -noupdate /hdl_top/axi_intf/arlock
add wave -noupdate /hdl_top/axi_intf/arcache
add wave -noupdate /hdl_top/axi_intf/arprot
add wave -noupdate /hdl_top/axi_intf/arqos
add wave -noupdate /hdl_top/axi_intf/arregion
add wave -noupdate /hdl_top/axi_intf/aruser
add wave -noupdate /hdl_top/axi_intf/arvalid
add wave -noupdate /hdl_top/axi_intf/arready
add wave -noupdate /hdl_top/axi_intf/rid
add wave -noupdate /hdl_top/axi_intf/rdata
add wave -noupdate /hdl_top/axi_intf/rresp
add wave -noupdate /hdl_top/axi_intf/rlast
add wave -noupdate /hdl_top/axi_intf/ruser
add wave -noupdate /hdl_top/axi_intf/rvalid
add wave -noupdate /hdl_top/axi_intf/rready
add wave -noupdate -divider {New Divider}
add wave -noupdate /hdl_top/DUT/s_apb_bus/paddr
add wave -noupdate /hdl_top/DUT/s_apb_bus/pwdata
add wave -noupdate /hdl_top/DUT/s_apb_bus/pwrite
add wave -noupdate /hdl_top/DUT/s_apb_bus/psel
add wave -noupdate /hdl_top/DUT/s_apb_bus/penable
add wave -noupdate /hdl_top/DUT/s_apb_bus/prdata
add wave -noupdate /hdl_top/DUT/s_apb_bus/pready
add wave -noupdate /hdl_top/DUT/s_apb_bus/pslverr
add wave -noupdate /hdl_top/DUT/s_spi_bus/paddr
add wave -noupdate /hdl_top/DUT/s_spi_bus/pwdata
add wave -noupdate /hdl_top/DUT/s_spi_bus/pwrite
add wave -noupdate /hdl_top/DUT/s_spi_bus/psel
add wave -noupdate /hdl_top/DUT/s_spi_bus/penable
add wave -noupdate /hdl_top/DUT/s_spi_bus/prdata
add wave -noupdate /hdl_top/DUT/s_spi_bus/pready
add wave -noupdate /hdl_top/DUT/s_spi_bus/pslverr
add wave -noupdate /hdl_top/DUT/DUT/HCLK
add wave -noupdate /hdl_top/DUT/DUT/HRESETn
add wave -noupdate /hdl_top/DUT/DUT/PADDR
add wave -noupdate /hdl_top/DUT/DUT/PWDATA
add wave -noupdate /hdl_top/DUT/DUT/PWRITE
add wave -noupdate /hdl_top/DUT/DUT/PSEL
add wave -noupdate /hdl_top/DUT/DUT/PENABLE
add wave -noupdate /hdl_top/DUT/DUT/PRDATA
add wave -noupdate /hdl_top/DUT/DUT/PREADY
add wave -noupdate /hdl_top/DUT/DUT/PSLVERR
add wave -noupdate /hdl_top/DUT/DUT/events_o
add wave -noupdate /hdl_top/DUT/DUT/spi_clk
add wave -noupdate /hdl_top/DUT/DUT/spi_csn0
add wave -noupdate /hdl_top/DUT/DUT/spi_csn1
add wave -noupdate /hdl_top/DUT/DUT/spi_csn2
add wave -noupdate /hdl_top/DUT/DUT/spi_csn3
add wave -noupdate /hdl_top/DUT/DUT/spi_mode
add wave -noupdate /hdl_top/DUT/DUT/spi_sdo0
add wave -noupdate /hdl_top/DUT/DUT/spi_sdo1
add wave -noupdate /hdl_top/DUT/DUT/spi_sdo2
add wave -noupdate /hdl_top/DUT/DUT/spi_sdo3
add wave -noupdate /hdl_top/DUT/DUT/spi_sdi0
add wave -noupdate /hdl_top/DUT/DUT/spi_sdi1
add wave -noupdate /hdl_top/DUT/DUT/spi_sdi2
add wave -noupdate /hdl_top/DUT/DUT/spi_sdi3
add wave -noupdate /hdl_top/DUT/DUT/spi_clk_div
add wave -noupdate /hdl_top/DUT/DUT/spi_clk_div_valid
add wave -noupdate /hdl_top/DUT/DUT/spi_status
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {254 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
